### ISSUE TITLE
Eager-loading and bandwidth consumption

### ISSUE THREAD

**Issue by jhabdas** [liwenyip/hugo-easy-gallery#13]
The auto-dimensioning feature is a nice affordance for users. Have you considered only fetching a few bytes of the image to get at the image headers and then cancelling the request as opposed to downloading all full-size images anytime someone encounters a gallery? I ask because it's a bit bandwidth intensive and will hurt users on prepaid mobile plans (like myself).

**Comment by liwenyip** [comment]
Hi Josh

Yes, I did try that approach but I found that the technique that was
supposed to cancel the full download didn't actually work. Happy for you to
point me to some example code, or submit a PR.

**Comment by jhabdas** [comment]
Thanks for the info, @liwenyip. I've only ever been able to accomplish the behavior with Ajax requests and AFIAK Fetch Standard doesn't support it—but you've got jQ so the cancellation may work there if you fetch the images asynchronously.

Gotta close this, though I'm also curious to know if you've tried the Hugo [`imageConfig`](https://gohugo.io/functions/imageconfig/) function given this addon targets internally-managed gallery images.
