### ISSUE TITLE
Gallery figurecaption not changing color with future imperfect theme

### ISSUE THREAD

**Issue by HenningTimm** [liwenyip/hugo-easy-gallery#14]
I tried using a gallery with the [future imperfect](https://themes.gohugo.io/future-imperfect/) theme, but the captions are shown in black on grey, making them hard to read. Using a different theme ([academic](https://themes.gohugo.io/academic)) the were white, as expected.

Changing `background`, `position`, `opacity` etc. in [`hugo-easy-gallery.css`](https://github.com/liwenyip/hugo-easy-gallery/blob/master/static/css/hugo-easy-gallery.css#L114) changes the caption properties, only changing the colour has no effect. I guess the theme sets the colour somewhere and it is not correctly overwritten, however, I do not know enough CSS to fix this.

**Comment by HenningTimm** [comment]
As a workaround:

I found out that in my version of the future.imperfect theme, in the file `static/css/add-on.css line 96`, the color value was set to black. This was the culprit overwriting the color and removing it (commenting it out) gave me the desired white text. 

However, I can not find the responsible file the hugo-future-imperfect repository. I will install a newer version of the theme to make sure that this bahaviour has not been patched in the newest version.

**Comment by liwenyip** [comment]
Hi @HenningTimm 

Another workaround would be to go to `\static\css\hugo-easy-gallery.css:121`

And change `color: #FFF;` to `color: #FFF !important;`

See https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity for explanation of how `!important` works.
