### ISSUE TITLE
Issue with ananke theme

### ISSUE THREAD

**Issue by LyzardKing** [liwenyip/hugo-easy-gallery#22]
Hi!
I'm building a website with the ananke theme..
I have an issue with the gallery (not the single images)
It won't show unless there's something else before in the page...specifically another picture, or an iframe..

EDIT: Actually...it's an issue with the theme, it isn't picking up  the width, but in responsive mode(on a phone) it works...
Can I set a width?

**Comment by LyzardKing** [comment]
I can apparently change the number of photos per row only here:
```
@media only screen and (min-width : 365px) {
    /* Tablet view: 2 tiles */
    .gallery .box {
        width: 50%;
        padding-bottom: 50%;
    }
}
```
But that doesn't really work...
Is it possible to do a "flexbox" like thing? And have the number of photos change with the screen size?

**Comment by liwenyip** [comment]
Should be possible - you'll need to set the number of photos per row for different screen sizes in the @media styles in the css file. If you need more help, please post a link to a test page and post your source code here. Thanks :-)

**Comment by polbins** [comment]
I found a fix in: https://github.com/budparr/gohugo-theme-ananke/issues/91
