### ISSUE TITLE
shortcode showcase

### ISSUE THREAD

**Issue by dkebler** [liwenyip/hugo-easy-gallery#4]
We both have some good shortcodes.  https://dkebler.github.io/landingpage-guide/#plugins

Interested in maintaining with me a shortcode repository/showcase?  My new generator would make it easy to build the showcase site.  In the plugins section there is nice modal based documentation for each shortcode (albeit I've only finished documenting two).  I've been thinking of creating a hugo "tools" github organization so here is a reason.

**Comment by liwenyip** [comment]
> Interested in maintaining with me a shortcode repository/showcase? 

Sounds good.
