### ISSUE TITLE
load-photoswipe.js and hugo-easy-gallery.css not loaded when BaseURL contains path

### ISSUE THREAD

**Issue by Anthop-2** [liwenyip/hugo-easy-gallery#44]
`load-photoswipe.js` and `hugo-easy-gallery.css` are not imported correctly when the site is configured with a path, for example: https://www.example.com/mysite/

This appears to be due to the fact that the paths are hard coded relative paths in `figure.html`, `gallery.html`, and `load-photoswipe.html`.

For example, in figure.html, changing:
>`<link rel="stylesheet" href="/css/hugo-easy-gallery.css" />`

to:
>`<link rel="stylesheet" href="{{ .Site.BaseURL }}/css/hugo-easy-gallery.css" />`

should address the issue.

**Comment by liwenyip** [comment]
Hi @Anthop-2 

Thanks for raising this.

Can you please test for me if the following works:

`<link rel="stylesheet" href="{{ "css/hugo-easy-gallery.css" | relURL }} />`

If that works it would be a more elegant solution.

**Comment by Mengesh** [comment]
It works.

**Comment by HartR** [comment]
> 
> 
> Hi @Anthop-2
> 
> Thanks for raising this.
> 
> Can you please test for me if the following works:
> 
> `<link rel="stylesheet" href="{{ "css/hugo-easy-gallery.css" | relURL }} />`
> 
> If that works it would be a more elegant solution.

Not working for me, getting the following error:

Error: Error building site: "/mnt/c/Users/hart.russell/Website/Mindful-Drivel/content/image-gallery.md:6:1": failed to render shortcode "gallery": failed to process shortcode: "/mnt/c/Users/hart.russell/Website/Mindful-Drivel/layouts/shortcodes/gallery.html:6:7": execute of template failed: html/template:shortcodes/gallery.html:6:7: {{if}} branches end in different contexts: {stateURL delimDoubleQuote urlPartPreQuery jsCtxRegexp attrURL elementNone <nil>}, {stateText delimNone urlPartNone jsCtxRegexp attrNone elementNone <nil>}

**Comment by Mengesh** [comment]
Actually `.js` should be also loaded with `relURL`. I created a pull request #47
