### ISSUE TITLE
Invalid HTML according to W3 Validator

### ISSUE THREAD

**Issue by phauer** [liwenyip/hugo-easy-gallery#5]
Hi Li-Wen,

first of all, I really like to thank you for this awesome library! Good job!

I just want to point you to the fact, that the [w3 validator](https://validator.w3.org) is not satisfied with the resulting html. It prints the following error:
```
Error: Element a not allowed as child of element figure in this context. (Suppressing further errors from this subtree.)
From line 308, column 5; to line 308, column 117
tion>↩    <a href="https://domain/image.JPG" itemprop="contentUrl"></a>↩ 
Contexts in which element a may be used:
Where phrasing content is expected.
Content model for element figure:
Flow content optionally including a figcaption child element.
```

The reason is that the `a` is the last child of the `figure` node. However, the `figcaption` should either be the first or last node of `figure` (see [here](http://stackoverflow.com/questions/37831262/is-figcaption-allowed-to-be-a-child-of-an-a-tag-in-html5)). Moving the `a` before the `figcaption` fixes the issue. The gallery still seems to work, but I'm not sure if this is the best fix, because there is this comment: 

> \<!-- put \<a\> last so it is stacked on top --\>

Is this an issue that should be fixed at all?

Cheers, Philipp

**Comment by liwenyip** [comment]
Thanks @phauer,

Valid HTML is a good idea. Let me look at this and get back to you.

**Comment by liwenyip** [comment]
@phauer: Done. 

The original reason for putting the <a> element last (on top) was to get the cursor to change to a hand when hovering over the figcaption. I've now done this using a css style instead.

**Comment by phauer** [comment]
Thank you, @liwenyip!
