### ISSUE TITLE
Shortcodes no longer work in Template files

### ISSUE THREAD

**Issue by beatricebock** [liwenyip/hugo-easy-gallery#7]
According to [Hugo](https://gohugo.io/extras/shortcodes/), shortcodes don't work in template files. Is there a workaround?

**Comment by liwenyip** [comment]
HEG doesn't normally need you to use a shortcode in a template file.

What are you trying to do?

In general, if you want to call a shortcode from a template, copy and paste the contents of the shortcode into your template.

**Comment by JorisEekhout** [comment]
I had the same question. I want to call the gallery shortcode from a single.html layout file. The directory argument should come from the front matter. Something like this:
`{{< gallery dir="/images/{{ .Params.dir }}" />}}`

But like beatrice said, shortcodes do not work in template files. Any ideas?

**Comment by liwenyip** [comment]
You'll need to copy `gallery.html` into your template file, or into partial template which you call from your main template.

You'll have to hard-code all the variables normally passed to the shortcode (i.e. every instance of `.Get`).

e.g. Change

`<div class="gallery caption-position-{{ with .Get "caption-position" | default "bottom" }}{{.}}{{end}} caption-effect-{{ with .Get "caption-effect" | default "slide" }}{{.}}{{end}} hover-effect-{{ with .Get "hover-effect" | default "zoom" }}{{.}}{{end}} {{ if ne (.Get "hover-transition") "none" }}hover-transition{{end}}" itemscope itemtype="http://schema.org/ImageGallery">`

to

`<div class="gallery caption-position-bottom caption-effect-slide hover-effect-zoom hover-transition" itemscope itemtype="http://schema.org/ImageGallery">`
